FROM mcr.microsoft.com/dotnet/aspnet:8.0.2 AS base
WORKDIR /app
RUN adduser -u 5561 --disabled-password --gecos "" amorphie-fact-clientuser && chown -R amorphie-fact-clientuser:amorphie-fact-clientuser /app
USER amorphie-fact-clientuser
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
ENV DOTNET_NUGET_SIGNATURE_VERIFICATION=false
COPY ["./amorphie.client/amorphie.client.csproj", "."]
RUN dotnet restore "./amorphie.client.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "./amorphie.client/amorphie.client.csproj" -c Release -o /app/build
FROM build AS publish
RUN dotnet publish "./amorphie.client/amorphie.client.csproj" -c Release -o /app/publish
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
EXPOSE 5000
ENV ASPNETCORE_URLS=http://+:5000
ENTRYPOINT ["dotnet", "amorphie.client.dll"]