FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["./amorphie.user/amorphie.user.csproj", "."]
RUN dotnet restore "./amorphie.user.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "./amorphie.user/amorphie.user.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "./amorphie.user/amorphie.user.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
EXPOSE 5000
ENV ASPNETCORE_URLS=http://+:5000
ENTRYPOINT ["dotnet", "amorphie.user.dll"]