apiVersion: apps/v1
kind: Deployment
metadata:
  name: amorphie-fact-user-zeebe
  namespace: amorphie-fact-user-zeebe
spec:
  selector:
    matchLabels:
      app: amorphie-fact-user-zeebe
  replicas: 1
  template:
    metadata:
      labels:
        app: amorphie-fact-user-zeebe
      annotations:
        dapr.io/app-id: amorphie-fact-user-zeebe
        dapr.io/enabled: 'true'
        dapr.io/app-port: '5000'
    spec:
      serviceAccountName: amorphie-fact-user-zeebeuser
      containers:
        - name: amorphie-fact-user-zeebe
          image: burganbank/amorphie.fact-user-zeebe:latest
          ports:
            - containerPort: 5000
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Test"
          - name: EnableApm
            value: "true"
          - name: TZ
            value: Europe/Istanbul
          - name: DAPR_STATE_STORE_NAME
            value: amorphie-cache
          - name: DAPR_SECRET_STORE_NAME
            value: user-secretstore
          - name: DAPR_ZEEBE_COMMAND_NAME
            value: workflow-zeebe-command
          resources:
            limits:
              cpu: "1"
              memory: "4096Mi"
            requests:
              cpu: "0.1"
              memory: "256Mi"


