apiVersion: v1
kind: Service
metadata:
  name: amorphie-fact-client
  namespace: amorphie-fact-client
spec:
  selector: 
    app: amorphie-fact-client
  ports:
    - port: 5000
      targetPort: 5000 